var nconf = require('nconf');

nconf.env([
  'STRAWPOLL_PORT', 
  'STRAWPOLL_MONGO_CONNECTION_STRING',
  'STRAWPOLL_TEST_MONGO_CONNECTION_STRING',
  'TWILIO_ACCOUNT_SID',
  'TWILIO_AUTH_TOKEN',
  'TWILIO_PHONE_NUMBER'
]);

module.exports = nconf;
